spring:
  zipkin:
    base-url: http://192.168.63.128:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    url: jdbc:mysql://192.168.63.128:3306/medicinedata?serverTimezone=UTC
    username: root
  redis:
    host: 192.168.63.128
    password: 123456
  session:
    timeout: 3600000
  rabbitmq:
    username: admin
    password: 123456
    addresses: amqp://192.168.63.128:5672
ribbon:
  eureka:
    enabled: true

feign:
  httpclient:
    connection-timeout: 3600000
logging:
  level:
    cn:
      project:
        mapper: debug
mybatis:
  type-aliases-package: cn.project.entity
