spring:
  application:
    name: user-client-service
server:
  port: 8022
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  eureka:
    enabled: true

logging:
  level:
    cn.controller: debug

